### ISSUE TITLE
I need help and encountered an error,Help me!

### ISSUE THREAD

**Issue by WREQI** [Macad3D/Macad3D#13]
![image](https://user-images.githubusercontent.com/35467304/124850758-cf10a480-dfd3-11eb-80c8-b02eed102540.png)
![image](https://user-images.githubusercontent.com/35467304/124850836-f4051780-dfd3-11eb-888b-56d484c1b621.png)
![image](https://user-images.githubusercontent.com/35467304/124850966-32023b80-dfd4-11eb-83f1-9bff91a04a6d.png)
Figure 1 is an error
Figure 2 is my occt folder
Figure 3 shows some third-party packages I downloaded
I don't know how to do it?

Is it necessary to use cmake to build occt7.5 and generate a bin directory below, so that there will be .dll files? Then use oct config D:\opencascade-7.5.0?

Help me!

**Comment by dipts** [comment]
The paths to the 3rd party packages are read from the build configuration of OCCT, by default the directories are expected to be on the same level as the OCCT directory.

Yes, if you have downloaded the source package from OCCT, the library has to be built first. I recommend you to download the windows installer from OCCT, all 3rd parties and precompiled release dlls are already there.

**Comment by WREQI** [comment]
![image](https://user-images.githubusercontent.com/35467304/124885765-2e87a800-e006-11eb-879d-4984f2bc0ef2.png)
Still receive an error
At the time of construction

**Comment by WREQI** [comment]
I use the downloaded occt windows installation package

**Comment by dipts** [comment]
The installer contains pre-built binaries for release configuration only. Try `build release` and the build should be successful. You have to build the debug version of OCCT yourself.
