### ISSUE TITLE
try to build from source

### ISSUE THREAD

**Issue by whanjit** [Macad3D/Macad3D#14]
![Capture777](https://user-images.githubusercontent.com/14107783/125064102-7b3cb300-e0da-11eb-86af-54c9cfb5f1ef.PNG)

**Comment by dipts** [comment]
It seems that you are missing some VS component like .Net 5 SDK or Cpp/CLI support. Try to open the solution in VS, maybe it can detect which components are missing.

**Comment by shao200** [comment]
I carefully downloaded the open source code, which took me a day and ended in failure. I reckon you're developing more code to stop others from running than it takes you to get your regular code running?

**Comment by dipts** [comment]
If you report something more specific about your problem, I would try to help you.
