### ISSUE TITLE
.net version of Macad3D

### ISSUE THREAD

**Issue by yong753** [Macad3D/Macad3D#15]
Hi, i want to use Macad3D for my own Project.

In your Homepage, Macad targets .net framework 4.8, so i create project also based on .netframework 4.8.

And i build source code and import dll files to my project

but i got this error message

--------------------------------------------------------------------------------------------------------
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly  'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' 
--------------------------------------------------------------------------------------------------------

It looks like depned on .net 5.0. So, I create new project based on .net 5.0.

Bui i got another error message like below

--------------------------------------------------------------------------------------------------------
System.BadImageFormatException: 'Could not load file or assembly 'Macad.Occt, Version=1.1.1295.3, Culture=neutral, PublicKeyToken=f3b86e0df7940e9a'. 
--------------------------------------------------------------------------------------------------------

What should i do?

**Comment by dipts** [comment]
Hi @yong753,

> In your Homepage, Macad targets .net framework 4.8

Version 1.0, which is available on the homepage, is built on .NET Framework 4.8. YOu can find the sources [here](https://github.com/Macad3D/Macad3D/tags).
The head of the main branch is already built on .NET 5.

> System.BadImageFormatException

This error message usually indicates that an x86 process is trying to load an x64 dll. Please make sure that you compile and start platform x64.

**Comment by yong753** [comment]
I got 1.0 version and it works perfectly in my project. 

I'll close this issue. 

Thanks for your help @dipts !
