### ISSUE TITLE
How does the view fill the center and fill the screen?

### ISSUE THREAD

**Issue by WREQI** [Macad3D/Macad3D#20]
![image](https://user-images.githubusercontent.com/35467304/148289362-c4066709-7f35-4494-a810-848e55f79814.png)

**Comment by dipts** [comment]
I'm afraid I don't know exactly what you mean. Can you elaborate on your question a bit more? What do you want to achieve?

**Comment by dipts** [comment]
Due to lack of feedback, reproduction is not possible.
