### ISSUE TITLE
Import stl file, save, but cannot open again.

### ISSUE THREAD

**Issue by RileyGe** [Macad3D/Macad3D#26]
System: Windows 10 20H2
Macad3D Version: 2.1(Revision 1467)

Open Macad3D -> Create New -> File -> Exchange -> Import into Model

Then select the file attached(I also tried another file, same result). Save the model. Then reopen again, will show the error message(pic 2).

![image](https://user-images.githubusercontent.com/26666371/192097720-c532a9e6-3acb-4a3f-8785-2164409f9957.png)

![image](https://user-images.githubusercontent.com/26666371/192097683-0dfd4944-b8a0-49dd-8967-ab97595f59bd.png)

[P31.zip](https://github.com/Macad3D/Macad3D/files/9638679/P31.zip)

**Comment by dipts** [comment]
This has been fixed in e2b984729ec56c6c463f27878ceb7ced1bcff6a5. Can you test again with the main branch? (No need to re-import, just load the .model file)

**Comment by RileyGe** [comment]
Yes, It is already fixed.

**Comment by dipts** [comment]
The fix is now also available in [Release 2.2](https://github.com/Macad3D/Macad3D/releases/tag/v2.2.1568).
