### ISSUE TITLE
Mirror with "Merge faces" option throw an Exception

### ISSUE THREAD

**Issue by zhyifei** [Macad3D/Macad3D#57]
When using the Mirror tool, with the  "Merge faces" option,  taking the top surface of a cylinder  as the datum,throw an exception:

<img width="515" alt="mirror_topface" src="https://github.com/Macad3D/Macad3D/assets/4772732/b060165d-ac98-4869-b712-c50aee75e996">

![image](https://github.com/Macad3D/Macad3D/assets/4772732/cdd226b5-8275-4740-850b-8b2ac2561b2a)

**Comment by dipts** [comment]
This is an OCCT issue. I have filed a ticket there (33421), the fix should be included in the next release.
