### ISSUE TITLE
How to add custom classes on Macad Occt？

### ISSUE THREAD

**Issue by wu-yi-hong** [Macad3D/Macad3D#64]
I added a custom class in the Macad Occt project, but it cannot be used after generating the DLL. So please tell me how I can add new classes on Macad Occt

**Comment by wu-yi-hong** [comment]
> Which class did you add? If this class comes from a previously unused package, a new .h/.cpp is created with the name of the package. This must be added to the Visual Studio project.

These are my actions：
![image](https://github.com/Macad3D/Macad3D/assets/73647662/312dc862-6e4f-4659-80e0-48923efec09a)
![e62aaf415ac11dc6eae79e89d1836d6](https://github.com/Macad3D/Macad3D/assets/73647662/e9ea5bc8-a649-420c-be91-a902b477ff22)
![16e7232d173183f97a623ecb41c1b2a](https://github.com/Macad3D/Macad3D/assets/73647662/1eb3e4d2-4f08-45b3-8725-7bec62ad74cc)
![image](https://github.com/Macad3D/Macad3D/assets/73647662/31054629-70e9-4490-9fe3-391c821c0ab3)

**Comment by wu-yi-hong** [comment]
OCC 7.8 not found TKSTL.dll , OCC 7.7 can found TKSTL.dll

**Comment by dipts** [comment]
The toolkit was renamed mit OCCT 7.8.

https://dev.opencascade.org/doc/overview/html/occt__upgrade.html#upgrade_780_tk_rework

**Comment by wu-yi-hong** [comment]
> The toolkit was renamed mit OCCT 7.8.
> 
> https://dev.opencascade.org/doc/overview/html/occt__upgrade.html#upgrade_780_tk_rework

Thank you, I have found the reason now. I am working on combining Occt and Vtk to complete the project. Now we can convert TopoDS-Shape to vtkPolyData, and everything has just begun.
