### ISSUE TITLE
Can Macad.Occt be used .NET FrameWork usage ?

### ISSUE THREAD

**Issue by wu-yi-hong** [Macad3D/Macad3D#65]
I want to work in WPF Using MacadOcct.dll and MacadManaged.dll in NET FrameWork but failed . It looks like it can only be done Used in .NET

**Comment by wu-yi-hong** [comment]
I have solved this problem by converting the C++project to NET FrameWork

**Comment by JawadJaber** [comment]
Kindly advise how did you converted the C++ to .NET Framework. I have changed the netcore to only cli but it did not work?
