### ISSUE TITLE
Model Origin Not Persisting After Move Operation

### ISSUE THREAD

**Issue by binlu979** [Macad3D/Macad3D#72]
After modifying the origin of the model, when using the move tool, the origin position reverts to its pre-modified state.

**Comment by dipts** [comment]
I don't understand your problem yet. Please describe exactly the expected behavior and the actual behavior. When it comes to pivot positions, screenshots and drawings can help.

And please use an English title.

**Comment by binlu979** [comment]
@dipts hello
I encountered an issue with modifying the origin of a model using the code. After setting the new origin, the model loads correctly and the origin is correctly displayed. However, when I try to move the model, it reverts to its original position, indicating that the origin change was not permanently applied.

The following code is used to modify the model's origin:
```c#
    TopoDS_Shape ShapeBrep = body.GetBRep();
  AIS_Shape aisShape = new AIS_Shape(ShapeBrep);
  var BoundBox =  ShapeBrep.BoundingBox(); 
  var BoxMini= BoundBox.CornerMin(); 
  Vec tranvec = new Vec(BoxMini, new Pnt(0, 0, 0)); 
  Trsf trsf = new Trsf(tranvec); 
  TopLoc_Location newloc = new TopLoc_Location(trsf);
  ShapeBrep.Location(newloc);
  aisShape.SetLocalTransformation(trsf);
```
Below is the correct display after modifying the model's origin:


However, when I slightly move the model using the move tool, it reverts to the original position as shown below:


This behavior suggests that the location transformation is not being preserved during subsequent manipulations. Please help me resolve this issue.

The following is after I modified the model's origin using the code,
![image](https://github.com/user-attachments/assets/f26af4cc-7915-481d-8af0-85d1144936ce)
but when I moved it slightly, it reverted to its original position.
![image](https://github.com/user-attachments/assets/acfd3a8a-3e2f-4fcd-bbef-e7ffcfd54a3d)

**Comment by dipts** [comment]
Thank you very much, I now understand exactly what you mean. 

The problem here is that both the brep and the locations are volatile. As soon as the transformation changes, the visualization is updated. Depending on the design of the shape stack, the shape is even recreated. The location entered in your code is therefore obsolete on both ends.

In order to achieve a permanent shift of the pivot, you would need a modifier in the shape stack that always applies this shift as soon as the shape is rebuilt. Macad does not include this modifier yet, although it would be a good idea to create something like this.

Another possibility is to collapse the shape stack. This saves the last brep created and uses it as the starting point for the shape creation from now on. The advantage is that the brep can be changed and persisted again. The disadvantage is that the entire shape stack is gone until the time of collapsing and therefore changes are no longer possible.

With the following script you can apply the change of the pivot to a selected body in this way:

```cs
using Macad.Interaction;
using Macad.Core;
using System.Linq;

var body = Selection.SelectedEntities.FirstOrDefault() as Body;
if (body == null)
{
  Messages.Error("Please select a body.");
  return;
}

Macad.Core.Toolkits.ConvertToSolid.CollapseShapeStack(new [] {body});
var solid = body.Shape as Solid;
var brep = solid.GetBRep();

var boundBox =  brep.BoundingBox(); 
var boxMin = boundBox.CornerMin(); 
Vec tranvec = new Vec(boxMin, new Pnt(0, 0, 0)); 
Trsf trsf = new Trsf(tranvec); 
TopLoc_Location newloc = new TopLoc_Location(trsf);
brep.Location(newloc);

solid.UpdateShape(brep);
solid.Invalidate(); 
```

I hope this helps you.

**Comment by binlu979** [comment]
### Issue Persisting After Using Provided Script

Thank you very much for your detailed response. However, after using the script you provided, I am still encountering the same issue. 

When I modify the model's origin using the provided script, it initially appears to be correct. However, as soon as I move the entity, the origin reverts to its original position. This suggests that the transformation is still not being permanently applied.

Here's the script I used based on your instructions:

```csharp
 public void Import()
 {
     var WorkingPlaneLocation = SpServer.Instance.WorkingPlane.Location;
     if (ImportDialog.Execute<IBodyImporter>(out var filename, out var importer))
     {
 
         if (importer.Extensions[0]== "step")
         {
           
             ((StepSettings)importer.Settings).ImportSingleBody = true;
         }
       
         if (!importer.DoImport(filename, out var newBodies))
         {
             ErrorDialogs.CannotImport(filename);
             return;
         } 
         foreach (var newBody in newBodies)
         {
             
            newBody.Position = WorkingPlaneLocation;
            CoreContext.Current?.Document?.Add(newBody);
       
             SetPoint(newBody);
         }
         
         InteractiveContext.Current.UndoHandler.Commit();
         InteractiveContext.Current.WorkspaceController?.Selection.SelectEntities(newBodies);
         ZoomFitAll();
     }

 }
 private void SetPoint(Body? body)
 {
     Macad.Core.Toolkits.ConvertToSolid.CollapseShapeStack(new[] { body });
     var solid = body?.Shape as Solid;
     var brep = solid?.GetBRep();
     var boundBox = brep.BoundingBox();
     var boxMin = boundBox.CornerMin();
     Vec tranvec = new Vec(boxMin, new Pnt(0, 0, 0));
     Trsf trsf = new Trsf(tranvec);
     TopLoc_Location newloc = new TopLoc_Location(trsf);
     brep?.Location(newloc);
     solid?.UpdateShape(brep);
     solid?.Invalidate(); 
 }
```
![recording](https://github.com/user-attachments/assets/2f9c4a7c-5c4f-4a6f-a9f6-8a6968d8d257)

Despite collapsing the shape stack and applying the transformation as suggested, the issue persists. Once I move the entity, it reverts to its original origin.

Could you please provide further guidance or suggest any additional steps I might take to ensure the origin change is permanent and does not revert upon moving the entity?

Thank you for your assistance.
