### ISSUE TITLE
Could you please tell me how well Macad3D supports winform?

### ISSUE THREAD

**Issue by ouleioulei** [Macad3D/Macad3D#75]
Could you please tell me how well Macad3D supports winform?

**Comment by ouleioulei** [comment]
Does anyone know, please?

**Comment by dipts** [comment]
The GUI of Macad3D is realized in WPF. Perhaps you can be a little more precise in your question about where you expect Winforms to be supported?

**Comment by ouleioulei** [comment]
![test2024-9-1](https://github.com/user-attachments/assets/17461b26-3ba8-4238-8a60-9a4df628f521)
Excuse me, among the dozen Macad3D projects shown in the picture, which ones can be directly used by Winform to develop new software without being limited to WPF?

**Comment by ouleioulei** [comment]
@dipts

**Comment by dipts** [comment]
I see. The WPF dependency is introduced in the interaction tier, where user controls (e.g. property panels) are defined. The core layer (Macad.Core) itself does not access WPF functionality. The Macad.Exchange module defines the settings dialogue, if these are not used, the module should also be usable under WinForms.

**Comment by ouleioulei** [comment]
> I see. The WPF dependency is introduced in the interaction tier (Macad.Interaction), where user controls (e.g. property panels) are defined. The core tier (Macad.Core) itself does not access WPF functionality. The Macad.Exchange module defines the settings dialogue, if these are not used, the module should also be usable under WinForms.

Thank you for your patient answer. Then the remaining items such as Macad.Occt that you did not mention are what Winform and WPF can use in general, right?

**Comment by dipts** [comment]
Macad.Occt contains the wrapper for the OCCT C++ library and belongs to the core tier. You can look at the project dependency of Macad.Core, everything that is referenced there is WPF free. Everything that is added to Macad.Interaction uses WPF.

Winforms has a control called [ElementHost](https://learn.microsoft.com/de-de/dotnet/api/system.windows.forms.integration.elementhost?view=windowsdesktop-8.0), which can be used to host WPF controls in Winforms. However, I don't know how well this works.

Another tip: If you build an application on Macad.Core, you have to create or derive an instance of `CoreContext`. That's all you basically need.

**Comment by ouleioulei** [comment]
> Macad.Occt contains the wrapper for the OCCT C++ library and belongs to the core tier. You can look at the project dependency of Macad.Core, everything that is referenced there is WPF free. Everything that is added to Macad.Interaction uses WPF.
> 
> Winforms has a control called [ElementHost](https://learn.microsoft.com/de-de/dotnet/api/system.windows.forms.integration.elementhost?view=windowsdesktop-8.0), which can be used to host WPF controls in Winforms. However, I don't know how well this works.
> 
> Another tip: If you build an application on Macad.Core, you have to create an instance of `CoreContext`. That's all you basically need.

Got it, thank you again for your patience!
