### ISSUE TITLE
Adding point to line sticking in sketch mode

### ISSUE THREAD

**Issue by mechanicCatman** [Macad3D/Macad3D#77]
Hi! First of all, I would like to thank you for the emergence of such a project and wish you good luck in its further development!

I would like to know if you plan to add a sticking algorithm in the future when hovering a point over a line? Currently, there is some displacement when you hover a point over the line.
![Screenshot 2024-09-13 183005](https://github.com/user-attachments/assets/9953c710-108d-4853-a399-d637fccf14d6)
![Screenshot 2024-09-13 183521](https://github.com/user-attachments/assets/9c5eebe4-e5f1-4af2-9412-0ea4179dd3fe)

**Comment by dipts** [comment]
Yes, in the next version the snapping system is significantly expanded. This also includes the function that points, when they are moved, snap to another segment or to the edges of other bodies in the scene.

This function is already included in the main branch. If you can build from source, you can already try it out.

**Comment by mechanicCatman** [comment]
> Yes, in the next version the snapping system is significantly expanded. This also includes the function that points, when they are moved, snap to another segment or to the edges of other bodies in the scene.
> 
> This function is already included in the main branch. If you can build from source, you can already try it out.

It's strange, for some reason the snapping system doesn't work for me, although I did a build yesterday from the main branch.

**Comment by dipts** [comment]
You're right, there still seem to be cases where it doesn't work. I'll take a look at that.
