### ISSUE TITLE
It seems that exporting to Gltf format is not supported.

### ISSUE THREAD

**Issue by lisl1233** [Macad3D/Macad3D#79]
Version 7.8 of the OCCT library already supports exporting files to the GlTF format, but Macad seems not to support it yet.

**Comment by dipts** [comment]
There is currently no exporter for glTF. For which use case do you need the format? Can you use OBJ instead? As Macad does not (yet) support materials, there would be no more in a glTF than in an OBJ or a U3D.

**Comment by lisl1233** [comment]
> 目前没有 glTF 导出器。您需要该格式用于哪些用例？您可以改用 OBJ 吗？由于 Macad 尚不支持材料，因此 glTF 中的内容不会比 OBJ 或 U3D 中的内容多。

Good, thank you for your response.Have a good day.
